package keeper

import (
	"context"
	"encoding/base64"
	"time"

	sdk "github.com/cosmos/cosmos-sdk/types"

	"ageverify/x/ageverify/types"
)

const dateTimeTolerance = 24 * time.Hour

func (k msgServer) SubmitAgeProof(
	goCtx context.Context,
	msg *types.MsgSubmitAgeProof,
) (*types.MsgSubmitAgeProofResponse, error) {
	ctx := sdk.UnwrapSDKContext(goCtx)

	// ---- Step 1: Decode proof from base64 ----
	proofBytes, err := base64.StdEncoding.DecodeString(msg.Proof)
	if err != nil {
		return nil, types.ErrInvalidProof.Wrap("base64 decode failed")
	}

	// ---- Step 2: Decode public witness from base64 ----
	witnessBytes, err := base64.StdEncoding.DecodeString(msg.PublicWitness)
	if err != nil {
		return nil, types.ErrInvalidWitness.Wrap("base64 decode failed")
	}

	// ---- Step 3: Validate current_date vs block time ----
	// Prevents prover from using a future date to fake age.
	proofDate, err := time.Parse("20060102", msg.CurrentDate)
	if err != nil {
		return nil, types.ErrDateMismatch.Wrap("invalid format, expected YYYYMMDD")
	}
	blockTime := ctx.BlockTime()
	diff := blockTime.Sub(proofDate)
	if diff < 0 {
		diff = -diff
	}
	if diff > dateTimeTolerance {
		return nil, types.ErrDateMismatch.Wrap("proof date too far from block time")
	}

	// ---- Step 4: Load verification key ----
	vk, err := LoadVerificationKey()
	if err != nil {
		return nil, types.ErrProofVerificationFailed.Wrap(err.Error())
	}

	// ---- Step 5: Verify ZK proof ----
	// groth16.Verify checks that the proof was generated by a valid circuit
	// (matching VK) and that the private inputs satisfy the constraints
	// (age >= 18) — all without seeing the birth date.
	if err := VerifyAgeProof(vk, proofBytes, witnessBytes); err != nil {
		return nil, types.ErrProofVerificationFailed.Wrap(err.Error())
	}

	// ---- Step 6: Store result ----
	k.Keeper.SetVerified(goCtx, msg.Creator, blockTime.Format(time.RFC3339))

	// ---- Step 7: Emit event ----
	ctx.EventManager().EmitEvent(sdk.NewEvent(
		"age_verified",
		sdk.NewAttribute("address", msg.Creator),
		sdk.NewAttribute("verified_at", blockTime.Format(time.RFC3339)),
	))

	return &types.MsgSubmitAgeProofResponse{}, nil
}
