package keeper

import (
	"bytes"
	"fmt"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	gnarkwitness "github.com/consensys/gnark/backend/witness"
)

// LoadVerificationKey deserializes VKBytes (from vk_embedded.go) into a
// gnark VerifyingKey. VKBytes is generated by: go run zk/setup/main.go
func LoadVerificationKey() (groth16.VerifyingKey, error) {
	vk := groth16.NewVerifyingKey(ecc.BN254)
	if _, err := vk.ReadFrom(bytes.NewReader(VKBytes)); err != nil {
		return nil, fmt.Errorf("failed to load verification key: %w", err)
	}
	return vk, nil
}

// VerifyAgeProof checks a ZK proof against the embedded verification key.
// Returns nil if valid, error otherwise.
func VerifyAgeProof(vk groth16.VerifyingKey, proofBytes, witnessBytes []byte) error {
	proof := groth16.NewProof(ecc.BN254)
	if _, err := proof.ReadFrom(bytes.NewReader(proofBytes)); err != nil {
		return fmt.Errorf("cannot deserialize proof: %w", err)
	}

	pubWitness, err := gnarkwitness.New(ecc.BN254.ScalarField())
	if err != nil {
		return fmt.Errorf("cannot create witness: %w", err)
	}
	if _, err := pubWitness.ReadFrom(bytes.NewReader(witnessBytes)); err != nil {
		return fmt.Errorf("cannot deserialize witness: %w", err)
	}

	if err := groth16.Verify(proof, vk, pubWitness); err != nil {
		return fmt.Errorf("proof verification failed: %w", err)
	}
	return nil
}
