package keeper

// VKBytes contains the serialized Groth16 verification key (BN254).
// Generated by: go run zk/setup/main.go
// DO NOT EDIT. Regenerate if the circuit (zk/circuit/age_circuit.go) changes.
//
// THIS IS A PLACEHOLDER. Replace with the real VKBytes generated by Z2.
var VKBytes = []byte{}
