package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"

	"zk-age-verify/zk/circuit"
)

// Run from repo root: go run zk/setup/main.go
func main() {
	// ---- Step 1: Compile circuit to R1CS ----
	fmt.Fprintln(os.Stderr, "Compiling circuit...")
	var c circuit.AgeCircuit
	ccs, err := frontend.Compile(ecc.BN254.ScalarField(), r1cs.NewBuilder, &c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Circuit compilation failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Circuit compiled: %d constraints\n", ccs.GetNbConstraints())

	// ---- Step 2: Groth16 trusted setup ----
	// SECURITY: In production, this MUST be a multi-party ceremony.
	// Anyone who knows the "toxic waste" from setup can forge proofs.
	fmt.Fprintln(os.Stderr, "Running Groth16 setup (this may take a moment)...")
	pk, vk, err := groth16.Setup(ccs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Setup failed: %v\n", err)
		os.Exit(1)
	}

	// ---- Step 3: Create output directory ----
	if err := os.MkdirAll("zk/keys", 0755); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Failed to create keys directory: %v\n", err)
		os.Exit(1)
	}

	// ---- Step 4: Save R1CS ----
	writeFile("zk/keys/circuit.r1cs", func(f *os.File) error { _, err := ccs.WriteTo(f); return err })

	// ---- Step 5: Save proving key ----
	writeFile("zk/keys/proving.key", func(f *os.File) error { _, err := pk.WriteTo(f); return err })

	// ---- Step 6: Save verification key ----
	writeFile("zk/keys/verification.key", func(f *os.File) error { _, err := vk.WriteTo(f); return err })

	// ---- Step 7: Export VK as Go source file ----
	var vkBuf bytes.Buffer
	if _, err := vk.WriteTo(&vkBuf); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Failed to serialize VK: %v\n", err)
		os.Exit(1)
	}
	goSrc := generateGoSource(vkBuf.Bytes())
	if err := os.WriteFile("zk/keys/vk_embedded.go", []byte(goSrc), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Failed to write vk_embedded.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintln(os.Stderr, "All keys saved to zk/keys/")
	fmt.Fprintln(os.Stderr, "Next: cp zk/keys/vk_embedded.go chain/x/ageverify/keeper/")
}

// writeFile creates a file and writes data to it using the provided function.
func writeFile(path string, writeFn func(*os.File) error) {
	f, err := os.Create(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Cannot create %s: %v\n", path, err)
		os.Exit(1)
	}
	defer f.Close()
	if err := writeFn(f); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: Cannot write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Saved: %s\n", path)
}

// generateGoSource creates a Go source file embedding the VK as a byte literal.
// Package is "keeper" so it drops directly into chain/x/ageverify/keeper/.
func generateGoSource(vkBytes []byte) string {
	var buf bytes.Buffer
	buf.WriteString("package keeper\n\n")
	buf.WriteString("// VKBytes contains the serialized Groth16 verification key (BN254).\n")
	buf.WriteString("// Generated by: go run zk/setup/main.go\n")
	buf.WriteString("// DO NOT EDIT. Regenerate if the circuit (zk/circuit/age_circuit.go) changes.\n")
	buf.WriteString("var VKBytes = []byte{")
	for i, b := range vkBytes {
		if i%16 == 0 {
			buf.WriteString("\n\t")
		}
		fmt.Fprintf(&buf, "0x%02x, ", b)
	}
	buf.WriteString("\n}\n")
	return buf.String()
}
